@baseUrl = http://localhost:8100
@token = ""
@adminToken = ""



#### LOGIN AS ADMIN TO GET TOKEN ####
# @name AdminLogin
POST {{baseUrl}}/admin
Content-Type: application/json

{
    "username": "admin",
    "password": "admin@1234"
}

@adminToken = {{AdminLogin.response.body.token}}


### GET ALL DOCTORS REQUEST ###
GET {{baseUrl}}/doctor
Accept: application/json
Authorization: Bearer {{adminToken}}


### PATIENT REGISTRE REQUEST ###
POST {{baseUrl}}/patient 
Content-Type: application/json

{
    "name": "Max Payne",
    "email": "maxpayne@mail.com",
    "phone": "5551232032",
    "password": "password@456",
    "age": 30,
    "address": "123 Main St",
    "gender": "male"
}

###CURL COMMAND###
curl -X POST http://localhost:8100/patient -H "Content-Type: application/json" -d '{"name":"Max Payne","email":"maxpayne@mail.com","phone":"5551232032","password":"password@456","age":30,"address":"123 Main St","gender":"male"}'


### PATIENT LOGIN REQUEST ###
POST {{baseUrl}}/patient/login
Content-Type: application/json

{
    "identifier": "maxpayne@mail.com",
    "password": "password@456"
}


### CURL COMMAND ###
curl -X POST http://localhost:8100/patient/login -H "Content-Type: application/json" -d '{"identifier":"maxpayne@mail.com","password":"password@456"}'


### PATIENT LOGIN WITH APPOINTMENTS ###
# @name PatientLogin
POST {{baseUrl}}/patient/login
Content-Type: application/json

{
    "identifier": "jane.doe@example.com",
    "password": "passJane1"
}

@token = {{PatientLogin.response.body.token}}



### GET PATIENT APPOINTMENTS REQUEST ###
GET {{baseUrl}}/patient/appointments?id=1
Accept: application/json
Authorization: Bearer {{token}}


### CURL COMMAND ###
curl -X GET "http://localhost:8100/patient/appointments?id=1" \
  -H "Accept: application/json" \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYW5lLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc2ODkxNDM4NCwiZXhwIjoxNzY5NTE5MTg0fQ.XjggyilypM4iHKDdJefzFZ3Wrl9Fl-Qkv3DIoN2l2nk"


### GET DOCTOR FILTER BY SPECIALTY & TIME REQUEST ###
### NEEDS TO BE ADMIN AUTHORIZED ###
GET {{baseUrl}}/doctor/filter?specialty=any&availableTime=2024-07-10T10:00
Accept: application/json
Authorization: Bearer {{adminToken}}


### GET DOCTOR FILTER BY SPECIALTY & TIME CURL COMMAND ###
GET {{baseUrl}}/doctor/filter?time=AM&specialty=Cardiologist
Accept: application/json
Authorization: Bearer {{adminToken}}