-- Appointments for TODAY (2026-01-20) for doctor_id = 1, patients 1-25
INSERT INTO appointment (doctor_id, patient_id, appointment_time, status) VALUES
(1, 1, CONCAT(CURDATE(), ' 09:00:00'), 0),
(1, 2, CONCAT(CURDATE(), ' 10:00:00'), 0),
(1, 3, CONCAT(CURDATE(), ' 11:00:00'), 1),
(1, 4, CONCAT(CURDATE(), ' 13:00:00'), 0),
(1, 5, CONCAT(CURDATE(), ' 14:00:00'), 1),
(1, 6, CONCAT(CURDATE(), ' 15:00:00'), 0),
(1, 7, CONCAT(CURDATE(), ' 16:00:00'), 0),
(1, 8, CONCAT(CURDATE(), ' 09:30:00'), 1),
(1, 9, CONCAT(CURDATE(), ' 10:30:00'), 0),
(1, 10, CONCAT(CURDATE(), ' 11:30:00'), 0);

-- Appointments for THIS WEEK (2026-01-20 to 2026-01-24) for doctor_id = 1, patients 1-25
-- Monday
INSERT INTO appointment (doctor_id, patient_id, appointment_time, status) VALUES
(1, 11, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 0 DAY) + INTERVAL 9 HOUR, 0),
(1, 12, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 0 DAY) + INTERVAL 10 HOUR, 1),
(1, 13, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 0 DAY) + INTERVAL 14 HOUR, 0);

-- Tuesday
INSERT INTO appointment (doctor_id, patient_id, appointment_time, status) VALUES
(1, 14, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 1 DAY) + INTERVAL 9 HOUR, 1),
(1, 15, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 1 DAY) + INTERVAL 11 HOUR, 0),
(1, 16, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 1 DAY) + INTERVAL 15 HOUR, 0);

-- Wednesday
INSERT INTO appointment (doctor_id, patient_id, appointment_time, status) VALUES
(1, 17, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 2 DAY) + INTERVAL 10 HOUR, 0),
(1, 18, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 2 DAY) + INTERVAL 13 HOUR, 1),
(1, 19, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 2 DAY) + INTERVAL 16 HOUR, 0);

-- Thursday
INSERT INTO appointment (doctor_id, patient_id, appointment_time, status) VALUES
(1, 20, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 3 DAY) + INTERVAL 9 HOUR, 0),
(1, 21, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 3 DAY) + INTERVAL 12 HOUR, 1),
(1, 22, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 3 DAY) + INTERVAL 14 HOUR, 0);

-- Friday
INSERT INTO appointment (doctor_id, patient_id, appointment_time, status) VALUES
(1, 23, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 4 DAY) + INTERVAL 10 HOUR, 1),
(1, 24, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 4 DAY) + INTERVAL 11 HOUR, 0),
(1, 25, DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 4 DAY) + INTERVAL 15 HOUR, 0);